### PR TITLE
Stable stack changelogs

### PR DESCRIPTION
**Pull request by ofalvai**

### CODE REVIEW

**Comment by radudanqonto** [comment]
@ofalvai can you revert this commit? It is affecting our CI jobs.

**Comment by ofalvai** [comment]
As much as we try to keep the stable stacks stable, we need to periodically make patch and minor version bumps to some tools because of bugfixes and security fixes, and because of other users expecting these changes.

We are doing a couple of things to make these changes less disruptive:
1. We maintain version manager aliases like `ruby 3.3` or `node 20` that you can safely rely on, these aliases always point to the specific version that's installed: https://stacks.bitrise.io/tips/tool-versions/
2. We provide [temporary rollback versions of stacks](https://devcenter.bitrise.io/en/infrastructure/build-stacks/stack-update-policy.html#using-the-previous-version-of-a-stack), so you can use the previous version of the stack for a limited time and adjust your workflows.

I hope this helps, and sorry for the breakage!

**Comment by radudanqonto** [comment]
Thank you for your reply, @ofalvai!

We tried pinning the alias 3.3 in our `.ruby-version`, but we had people encountering issues locally with `rbenv`. When we cd to the project's directory, we get an error about `3.3` being an incompatible Ruby version (version is not found).

**Comment by ofalvai** [comment]
Weird, I thought `rbenv` supports version aliases. `asdf` (via the [alias plugin](https://github.com/andrewthauer/asdf-alias)) and `mise` do. So that's one option, but I also see [a project that adds alias support for rbenv](http://rawsyntax.com/blog/compatible-ruby-version-with-rbenv-aliases/) as well.

**Pull request merged**
